todoproject/todoapp/urls.py
from . import views
from django.urls import path
app_name='todoapp'

urlpatterns = [
    path('',views.home,name='home'),
    path('delete/<int:taskid>/',views.delete,name='delete'),
    path('update/<int:id>/',views.update,name='update'),
    path('cbvhome/',views.TasklistView.as_view(),name='cbvhome'),
    path('cbvdetail/<int:pk>/',views.Detailview.as_view(),name='cbvdetail'),
    path('cbvupdate/<int:pk>/',views.updateview.as_view(),name='cbvupdate'),
    path('cbvdelete/<int:pk>/',views.deleteview.as_view(),name='cbvdelete'),
]

todoproject/todoproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from todoproject import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('todoapp.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

todoproject/todoapp/models.py
from django.db import models

# Create your models here.
class task(models.Model):
    name=models.CharField(max_length=250)
    priority=models.TextField()
    date=models.DateField()

    def __str__(self):
        return self.name

todoproject/todoapp/views.py
from .form import taskform
from django.shortcuts import render,redirect
from .models import task
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import UpdateView,DeleteView



class TasklistView(ListView):
    model= task
    template_name='home.html'
    context_object_name='task'

class Detailview(DetailView):
    model=task
    template_name='detail.html'
    context_object_name='task'

class updateview(UpdateView):
    model=task
    template_name='update.html'
    context_object_name='task'
    fields=('name','priority','date')

    def get_success_url(self):
        return reverse_lazy('cbvdetail',kwargs={'pk':self.object.id})

class deleteview(DeleteView):
    model=task
    template_name='delete.html'
    success_url= reverse_lazy('cbvhome')

# Create your views here.


def home(request):
    task2=task.objects.all()
    if request.method=='POST':
        name=request.POST.get('task','')
        priority=request.POST.get('priority','')
        date=request.POST.get('date','')
        task1=task(name=name,priority=priority,date=date)
        task1.save()
    return render(request,'home.html',{'task':task2})

def delete(request,taskid):
    task2=task.objects.get(id=taskid)
    if request.method=='POST':
        task2.delete()
        return redirect('/')
    return render(request,'delete.html')

def update(request,id):
    task3=task.objects.get(id=id)
    form1=taskform(request.POST or None,instance=task3)
    if form1.is_valid():
        form1.save()
        return redirect('/')
    return render(request,'update.html',{'form':form1,'task':task3})

todoproject/todoapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ToDo Application</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

todoproject/todoapp/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" class=" p-3 shadow">
    {% csrf_token %}
        <div class="form-group" >
            <h2>Are you sure ?</h2>
        </div> <br>
        <div class="form-group">
            <button type="submit" class="btn btn-danger">yes</button>
        </div>
{% endblock %}

todoproject/todoapp/templates/detail.html
{% extends 'base.html' %}
{% block content %}
<form action="" method="post" >
    {% csrf_token %}
    <div class="col-md-12">
        <div class="card shadow">
            <div class="card-body">
              <h5 class="card-title"> {{task.name}}</h5>
              <p class="card-text"><b>{{task.priority}}</b></p>
              <p class="card-text"><b>{{task.date}}</b></p>
              <a href="{% url 'todoapp:delete' task.id %}" class="btn btn-success">Done</a>
              <a href="{% url 'todoapp:update' task.id %}" class="btn btn-warning">update</a>
            </div>
        </div>
        <br>
    </div>
{% endblock %}

todoproject/todoapp/templates/home.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="banner">
                <div class="banner-text">
                    <h1>ToDo</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
       <div class="col-md-6">
            <form action="" method="post" class=" p-3 shadow">
                {% csrf_token %}
                    <div class="form-group" >
                        <input type="text" class="form-control" placeholder="Task" name="task">
                    </div> <br>
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Priority" name="priority" >
                    </div> <br>
                    <div class="form-group">
                        <input type="date" class="form-control" name="date" >
                    </div> <br>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success" style="background-color: cadetblue;">Submit</button>
                    </div>
            </form>
        </div>
        <div class="col-md-6">
            <h3>Task to complete</h3> <br>
            {% for i in task %}
            <div class=" shadow card">
                <div class="card-body">
                  <h5 class="card-title"> {{i.name}}</h5>
                  <p class="card-text"><b>{{i.priority}}</b></p>
                  <p class="card-text"><b>{{i.date}}</b></p>
                  <a href="{% url 'todoapp:delete' i.id %}" class="btn btn-success">Done</a>
                  <a href="{% url 'todoapp:update' i.id %}" class="btn btn-warning">update</a>
                </div>
            </div>
            <br>
            {% endfor %}
        </div>
       
        
    </div>
        
</div>
{% endblock %}

todoproject/todoapp/templates/update.html
{% extends 'base.html' %}
{% block content %}
<div class="col-md-12">
    <div class="card shadow">
        <div class="card-header">
            <div class="card-body">
                <h5 class="card-title">{{task.name}} Time</h5>
                <form action="" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <div class="form-group">
                        <button type="submit" class="btn btn-success" style="background-color: cadetblue;">Submit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <br>
</div>
{% endblock %}